### ISSUE TITLE
Currently we only support one "Period Designator" for example `D`, `M` `W` and `Y`, should we support combinations?

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay/core#13]
For example:

- `P1Y6M` » Every year and a half
- `P2Y6M` » Every two and a half years

https://github.com/wp-pay/core/blob/da88cbdbf6e914fb11b759fd6c8b24d30734d91c/src/Subscriptions/SubscriptionPhase.php#L68-L86

This might be easy to support, but we have to change the calculation of the period date / end date:

https://github.com/wp-pay/core/blob/da88cbdbf6e914fb11b759fd6c8b24d30734d91c/src/Subscriptions/SubscriptionPhase.php#L391

https://github.com/wp-pay/core/blob/da88cbdbf6e914fb11b759fd6c8b24d30734d91c/src/Subscriptions/SubscriptionPhase.php#L411

**Comment by rvdsteege** [comment]
Work in progress to work with `DateInterval` specification instead of single interval `value` and `unit`.

In core:
- [Use date interval specification for interval.](https://github.com/wp-pay/core/commit/50b3f718a29d8845f1340bc01dde36db7865745e)
- [Updated next payment and next date calculations.](https://github.com/wp-pay/core/commit/09f429f33622510f2c0835b0b6860f63fa689c3c)

In extensions:
- https://github.com/wp-pay-extensions/gravityforms/commit/d99e9bd72b79052b11638bae7b9326d8f880cd2a
- https://github.com/wp-pay-extensions/memberpress/commit/1afcb8b76f48397ec6c41894547fb0bbc1cd74bd
- https://github.com/wp-pay-extensions/restrict-content-pro/commit/8cd47237b5e409bd10c6196a83e7932d8350ab01

s2Member and WooCommerce still need to be updated.

**Comment by rvdsteege** [comment]
Updated s2Member and WooCommerce:

- https://github.com/wp-pay-extensions/s2member/commit/5d4fd803f175efea2fd4f19303f463fd8a43d79a
- https://github.com/wp-pay-extensions/woocommerce/commit/e2ce8b5315a2e33f87d0a78c0caf60f390263b45
